"""Initial Migration

Revision ID: 45044c558e86
Revises: 
Create Date: 2024-08-04 20:37:51.997273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45044c558e86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('expired', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timer')
    # ### end Alembic commands ###
